name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.x'
        
    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        CGO_ENABLED: 1
      run: go test -v -coverpkg=./... -coverprofile=coverage.out ./...

    - name: Generate Coverage Badge
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+')
        echo "## Coverage: ${COVERAGE}%" >> $GITHUB_STEP_SUMMARY
